# Generated by Django 2.2.5 on 2019-09-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('publishDate', models.DateField()),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
